name: Toolshop API Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        # Newman sẽ tự động dùng URL mới trong collection của bạn
        run: newman run postman/toolshop-api-tests.json
